const vocabulaire = [
    // Salutations
    { fr: "Bonjour", pl: "Dzień dobry", niveau: 1, categorie: "Salutations" },
    { fr: "Salut", pl: "Cześć", niveau: 1, categorie: "Salutations" },
    { fr: "Au revoir", pl: "Do widzenia", niveau: 1, categorie: "Salutations" },
    { fr: "Bonsoir", pl: "Dobry wieczór", niveau: 1, categorie: "Salutations" },
    { fr: "Bonne nuit", pl: "Dobranoc", niveau: 1, categorie: "Salutations" },
    { fr: "À plus tard", pl: "Na razie", niveau: 1, categorie: "Salutations" },
    { fr: "À bientôt", pl: "Do zobaczenia", niveau: 1, categorie: "Salutations" },
    { fr: "À demain", pl: "Do jutra", niveau: 1, categorie: "Salutations" },
    { fr: "Bienvenue", pl: "Witamy", niveau: 1, categorie: "Salutations" },

    // Politesse et Base
    { fr: "Merci", pl: "Dziękuję", niveau: 1, categorie: "Politesse et Base" },
    { fr: "S'il vous plaît", pl: "Proszę", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Pardon / Excusez-moi", pl: "Przepraszam", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Oui", pl: "Tak", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Non", pl: "Nie", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Je ne sais pas", pl: "Nie wiem", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Bien", pl: "Dobrze", niveau: 1, categorie: "Politesse et Base" },
    { fr: "De rien", pl: "Nie ma za co", niveau: 1, categorie: "Politesse et Base" },
    { fr: "D'accord", pl: "Dobra", niveau: 1, categorie: "Politesse et Base" },
    { fr: "Pas de problème", pl: "Nie ma problemu", niveau: 1, categorie: "Politesse et Base" },

    // Pronoms Sujets
    { fr: "Je", pl: "Ja", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Tu", pl: "Ty", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Il", pl: "On", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Elle", pl: "Ona", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "On / Cela", pl: "Ono", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Nous", pl: "My", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Vous (pluriel)", pl: "Wy", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Ils (hommes)", pl: "Oni", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Elles", pl: "One", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Monsieur", pl: "Pan", niveau: 1, categorie: "Pronoms Sujets" },
    { fr: "Madame", pl: "Pani", niveau: 1, categorie: "Pronoms Sujets" },

    // Pronoms Possessifs
    { fr: "Mon / Ma", pl: "Mój / Moja", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Ton / Ta", pl: "Twój / Twoja", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Son / Sa (à lui)", pl: "Jego", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Son / Sa (à elle)", pl: "Jej", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Notre", pl: "Nasz / Nasza", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Votre", pl: "Wasz / Wasza", niveau: 1, categorie: "Pronoms Possessifs" },
    { fr: "Leur", pl: "Ich", niveau: 1, categorie: "Pronoms Possessifs" },

    // Temps : Moments
    { fr: "Jour", pl: "Dzień", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Nuit", pl: "Noc", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Matin", pl: "Rano", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Soir", pl: "Wieczór", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Aujourd'hui", pl: "Dzisiaj", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Demain", pl: "Jutro", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Après-demain", pl: "Pojutrze", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Hier", pl: "Wczoraj", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Avant-hier", pl: "Przedwczoraj", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Maintenant", pl: "Teraz", niveau: 1, categorie: "Temps : Moments" },
    { fr: "Plus tard", pl: "Później", niveau: 1, categorie: "Temps : Moments" },

    // Temps : Fréquence et Durée
    { fr: "Heure", pl: "Godzina", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Minute", pl: "Minuta", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Seconde", pl: "Sekunda", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Semaine", pl: "Tydzień", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Mois", pl: "Miesiąc", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Année", pl: "Rok", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Toujours", pl: "Zawsze", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Souvent", pl: "Często", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Parfois", pl: "Czasami", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Rarement", pl: "Rzadko", niveau: 1, categorie: "Temps : Fréquence et Durée" },
    { fr: "Jamais", pl: "Nigdy", niveau: 1, categorie: "Temps : Fréquence et Durée" },

    // Questions
    { fr: "Qui", pl: "Kto", niveau: 1, categorie: "Questions" },
    { fr: "Quoi", pl: "Co", niveau: 1, categorie: "Questions" },
    { fr: "Où", pl: "Gdzie", niveau: 1, categorie: "Questions" },
    { fr: "Quand", pl: "Kiedy", niveau: 1, categorie: "Questions" },
    { fr: "Pourquoi", pl: "Dlaczego", niveau: 1, categorie: "Questions" },
    { fr: "Comment", pl: "Jak", niveau: 1, categorie: "Questions" },
    { fr: "Combien (quantité)", pl: "Ile", niveau: 1, categorie: "Questions" },
    { fr: "Lequel", pl: "Który", niveau: 1, categorie: "Questions" },

    // Mots de liaison
    { fr: "Et", pl: "I / A", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Mais", pl: "Ale", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Parce que", pl: "Bo / Ponieważ", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Ou", pl: "Albo / Lub", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Si (condition)", pl: "Jeśli", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Donc", pl: "Więc", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Aussi", pl: "Też / Także", niveau: 1, categorie: "Mots de liaison" },
    { fr: "Très", pl: "Bardzo", niveau: 1, categorie: "Mots de liaison" },

    // Adjectifs : Description physique
    { fr: "Grand", pl: "Duży", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Petit", pl: "Mały", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Haut", pl: "Wysoki", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Bas / Court", pl: "Niski", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Gros", pl: "Gruby", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Mince", pl: "Chudy", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Nouveau", pl: "Nowy", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Vieux", pl: "Stary", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Jeune", pl: "Młody", niveau: 1, categorie: "Adjectifs : Physique" },
    { fr: "Beau", pl: "Piękny", niveau: 1, categorie: "Adjectifs : Physique" },

    // Adjectifs : Qualités et Défauts
    { fr: "Bon", pl: "Dobry", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Mauvais", pl: "Zły", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Intelligent", pl: "Mądry", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Stupide", pl: "Głupi", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Sympathique", pl: "Miły", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Drôle", pl: "Zabawny", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Facile", pl: "Łatwy", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Difficile", pl: "Trudny", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Fort", pl: "Silny", niveau: 1, categorie: "Adjectifs : Qualités" },
    { fr: "Faible", pl: "Słaby", niveau: 1, categorie: "Adjectifs : Qualités" },

    // Adjectifs : États et Sensations
    { fr: "Chaud", pl: "Gorący", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Froid", pl: "Zimny", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Cher", pl: "Drogi", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Bon marché", pl: "Tani", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Rapide", pl: "Szybki", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Lent", pl: "Wolny", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Ouvert", pl: "Otwarty", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Fermé", pl: "Zamknięty", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Propre", pl: "Czysty", niveau: 1, categorie: "Adjectifs : États" },
    { fr: "Sale", pl: "Brudny", niveau: 1, categorie: "Adjectifs : États" },

    // Lieux : La Ville
    { fr: "Ville", pl: "Miasto", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Village", pl: "Wieś", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Rue", pl: "Ulica", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Place", pl: "Plac", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Parc", pl: "Park", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Pont", pl: "Most", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Centre-ville", pl: "Centrum", niveau: 1, categorie: "Lieux : La Ville" },
    { fr: "Quartier", pl: "Dzielnica", niveau: 1, categorie: "Lieux : La Ville" },

    // Lieux : Bâtiments et Commerces
    { fr: "Maison", pl: "Dom", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Appartement", pl: "Mieszkanie", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Travail", pl: "Praca", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "École", pl: "Szkoła", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Magasin", pl: "Sklep", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Hôpital", pl: "Szpital", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Restaurant", pl: "Restauracja", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Hôtel", pl: "Hotel", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Banque", pl: "Bank", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Pharmacie", pl: "Apteka", niveau: 1, categorie: "Lieux : Bâtiments" },
    { fr: "Église", pl: "Kościół", niveau: 1, categorie: "Lieux : Bâtiments" },

    // Famille proche
    { fr: "Mère", pl: "Matka / Mama", niveau: 1, categorie: "Famille proche" },
    { fr: "Père", pl: "Ojciec / Tata", niveau: 1, categorie: "Famille proche" },
    { fr: "Sœur", pl: "Siostra", niveau: 1, categorie: "Famille proche" },
    { fr: "Frère", pl: "Brat", niveau: 1, categorie: "Famille proche" },
    { fr: "Fille (enfant)", pl: "Córka", niveau: 1, categorie: "Famille proche" },
    { fr: "Fils", pl: "Syn", niveau: 1, categorie: "Famille proche" },
    { fr: "Parents", pl: "Rodzice", niveau: 1, categorie: "Famille proche" },
    { fr: "Mari", pl: "Mąż", niveau: 1, categorie: "Famille proche" },
    { fr: "Femme (épouse)", pl: "Żona", niveau: 1, categorie: "Famille proche" },
    { fr: "Enfant", pl: "Dziecko", niveau: 1, categorie: "Famille proche" },

    // Famille éloignée et Personnes
    { fr: "Grand-mère", pl: "Babcia", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Grand-père", pl: "Dziadek", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Oncle", pl: "Wujek", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Tante", pl: "Ciocia", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Homme", pl: "Mężczyzna", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Femme", pl: "Kobieta", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Garçon", pl: "Chłopiec", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Fille", pl: "Dziewczyna", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Ami", pl: "Przyjaciel", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Amie", pl: "Przyjaciółka", niveau: 1, categorie: "Famille éloignée" },
    { fr: "Famille", pl: "Rodzina", niveau: 1, categorie: "Famille éloignée" },

    // Nourriture : Repas et Base
    { fr: "Petit-déjeuner", pl: "Śniadanie", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Déjeuner", pl: "Obiad", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Dîner", pl: "Kolacja", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Pain", pl: "Chleb", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Viande", pl: "Mięso", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Poulet", pl: "Kurczak", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Poisson", pl: "Ryba", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Fromage", pl: "Ser", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Œuf", pl: "Jajko", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Sel", pl: "Sól", niveau: 1, categorie: "Nourriture : Base" },
    { fr: "Sucre", pl: "Cukier", niveau: 1, categorie: "Nourriture : Base" },

    // Nourriture : Fruits et Légumes
    { fr: "Pomme", pl: "Jabłko", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Banane", pl: "Banan", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Orange", pl: "Pomarańcza", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Fraise", pl: "Truskawka", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Pomme de terre", pl: "Ziemniak", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Tomate", pl: "Pomidor", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Oignon", pl: "Cebula", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Carotte", pl: "Marchew", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },
    { fr: "Salade", pl: "Sałata", niveau: 1, categorie: "Nourriture : Fruits et Légumes" },

    // Nourriture : Boissons
    { fr: "Eau", pl: "Woda", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Lait", pl: "Mleko", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Café", pl: "Kawa", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Thé", pl: "Herbata", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Jus", pl: "Sok", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Bière", pl: "Piwo", niveau: 1, categorie: "Nourriture : Boissons" },
    { fr: "Vin", pl: "Wino", niveau: 1, categorie: "Nourriture : Boissons" },

    // Couleurs
    { fr: "Rouge", pl: "Czerwony", niveau: 1, categorie: "Couleurs" },
    { fr: "Bleu", pl: "Niebieski", niveau: 1, categorie: "Couleurs" },
    { fr: "Vert", pl: "Zielony", niveau: 1, categorie: "Couleurs" },
    { fr: "Jaune", pl: "Żółty", niveau: 1, categorie: "Couleurs" },
    { fr: "Noir", pl: "Czarny", niveau: 1, categorie: "Couleurs" },
    { fr: "Blanc", pl: "Biały", niveau: 1, categorie: "Couleurs" },
    { fr: "Gris", pl: "Szary", niveau: 1, categorie: "Couleurs" },
    { fr: "Rose", pl: "Różowy", niveau: 1, categorie: "Couleurs" },
    { fr: "Orange", pl: "Pomarańczowy", niveau: 1, categorie: "Couleurs" },
    { fr: "Marron", pl: "Brązowy", niveau: 1, categorie: "Couleurs" },

    // Directions et Positions
    { fr: "Ici", pl: "Tutaj", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Là", pl: "Tam", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Gauche", pl: "Lewo", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Droite", pl: "Prawo", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Tout droit", pl: "Prosto", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Haut", pl: "Góra", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Bas", pl: "Dół", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Devant", pl: "Przed", niveau: 1, categorie: "Directions et Positions" },
    { fr: "Derrière", pl: "Za", niveau: 1, categorie: "Directions et Positions" },
    { fr: "À côté de", pl: "Obok", niveau: 1, categorie: "Directions et Positions" },

    // Santé et État
    { fr: "Malade", pl: "Chory", niveau: 1, categorie: "Santé et État" },
    { fr: "En pleine forme", pl: "Zdrowy", niveau: 1, categorie: "Santé et État" },
    { fr: "Fatigué", pl: "Zmęczony", niveau: 1, categorie: "Santé et État" },
    { fr: "Occupé", pl: "Zajęty", niveau: 1, categorie: "Santé et État" },
    { fr: "Libre / Dispo", pl: "Wolny", niveau: 1, categorie: "Santé et État" },
    { fr: "Gêné", pl: "Zawstydzony", niveau: 1, categorie: "Santé et État" },
    { fr: "J'ai faim", pl: "Jestem głodny", niveau: 1, categorie: "Santé et État" },
    { fr: "J'ai soif", pl: "Jestem spragniony", niveau: 1, categorie: "Santé et État" },
    { fr: "Médicament", pl: "Lek", niveau: 1, categorie: "Santé et État" },

    // Corps Humain : Tête
    { fr: "Tête", pl: "Głowa", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Visage", pl: "Twarz", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Œil", pl: "Oko", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Oreille", pl: "Ucho", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Nez", pl: "Nos", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Bouche", pl: "Usta", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Cheveux", pl: "Włosy", niveau: 1, categorie: "Corps Humain : Tête" },
    { fr: "Dent", pl: "Ząb", niveau: 1, categorie: "Corps Humain : Tête" },

    // Corps Humain : Membres
    { fr: "Main", pl: "Ręka", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Jambe", pl: "Noga", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Bras", pl: "Ramię", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Pied", pl: "Stopa", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Dos", pl: "Plecy", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Ventre", pl: "Brzuch", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Cœur", pl: "Serce", niveau: 1, categorie: "Corps Humain : Membres" },
    { fr: "Sang", pl: "Krew", niveau: 1, categorie: "Corps Humain : Membres" },

    // Présentations
    { fr: "Prénom", pl: "Imię", niveau: 1, categorie: "Présentations" },
    { fr: "Nom de famille", pl: "Nazwisko", niveau: 1, categorie: "Présentations" },
    { fr: "Âge", pl: "Wiek", niveau: 1, categorie: "Présentations" },
    { fr: "D'où viens-tu ?", pl: "Skąd jesteś?", niveau: 1, categorie: "Présentations" },
    { fr: "Je suis de France", pl: "Jestem z Francji", niveau: 1, categorie: "Présentations" },
    { fr: "Enchanté", pl: "Miło mi", niveau: 1, categorie: "Présentations" },
    { fr: "Comment t'appelles-tu ?", pl: "Jak masz na imię?", niveau: 1, categorie: "Présentations" },
    { fr: "Je m'appelle", pl: "Mam na imię", niveau: 1, categorie: "Présentations" },

    // Hobbies et Loisirs
    { fr: "Sport", pl: "Sport", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Musique", pl: "Muzyka", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Cinéma", pl: "Kino", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Lecture", pl: "Czytanie", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Voyage", pl: "Podróż", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Danse", pl: "Taniec", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Dessin", pl: "Rysunek", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Photographie", pl: "Fotografia", niveau: 1, categorie: "Hobbies et Loisirs" },
    { fr: "Théâtre", pl: "Teatr", niveau: 1, categorie: "Hobbies et Loisirs" },

    // Jeux Vidéos : Base
    { fr: "Jeu", pl: "Gra", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Joueur", pl: "Gracz", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Console", pl: "Konsola", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Manette", pl: "Pad", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Clavier", pl: "Klawiatura", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Souris", pl: "Myszka", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Écran", pl: "Ekran", niveau: 1, categorie: "Jeux Vidéos : Base" },
    { fr: "Multijoueur", pl: "Wieloosobowy", niveau: 1, categorie: "Jeux Vidéos : Base" },

    // Jeux Vidéos : Action
    { fr: "Gagner", pl: "Wygrać", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Perdre", pl: "Przegrać", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Niveau", pl: "Poziom", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Ennemi", pl: "Wróg", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Personnage", pl: "Postać", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Arme", pl: "Broń", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Santé (HP)", pl: "Zdrowie", niveau: 1, categorie: "Jeux Vidéos : Action" },
    { fr: "Sauvegarder", pl: "Zapisać", niveau: 1, categorie: "Jeux Vidéos : Action" },

    // Vêtements
    { fr: "Vêtements", pl: "Ubrania", niveau: 1, categorie: "Vêtements" },
    { fr: "Pantalon", pl: "Spodnie", niveau: 1, categorie: "Vêtements" },
    { fr: "Chemise", pl: "Koszula", niveau: 1, categorie: "Vêtements" },
    { fr: "T-shirt", pl: "Koszulka", niveau: 1, categorie: "Vêtements" },
    { fr: "Chaussures", pl: "Buty", niveau: 1, categorie: "Vêtements" },
    { fr: "Veste", pl: "Kurtka", niveau: 1, categorie: "Vêtements" },
    { fr: "Robe", pl: "Sukienka", niveau: 1, categorie: "Vêtements" },
    { fr: "Jupe", pl: "Spódnica", niveau: 1, categorie: "Vêtements" },
    { fr: "Chaussettes", pl: "Skarpetki", niveau: 1, categorie: "Vêtements" },
    { fr: "Chapeau", pl: "Kapelusz", niveau: 1, categorie: "Vêtements" },

    // Animaux : Domestiques
    { fr: "Chien", pl: "Pies", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Chat", pl: "Kot", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Oiseau", pl: "Ptak", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Poisson", pl: "Ryba", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Lapin", pl: "Królik", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Cheval", pl: "Koń", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Vache", pl: "Krowa", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Cochon", pl: "Świnia", niveau: 1, categorie: "Animaux : Domestiques" },
    { fr: "Poule", pl: "Kura", niveau: 1, categorie: "Animaux : Domestiques" },

    // Animaux : Sauvages
    { fr: "Ours", pl: "Niedźwiedź", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Loup", pl: "Wilk", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Renard", pl: "Lis", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Lion", pl: "Lew", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Tigre", pl: "Tygrys", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Éléphant", pl: "Słoń", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Singe", pl: "Małpa", niveau: 1, categorie: "Animaux : Sauvages" },
    { fr: "Serpent", pl: "Wąż", niveau: 1, categorie: "Animaux : Sauvages" },

    // Maison : Pièces
    { fr: "Chambre", pl: "Sypialnia", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Cuisine", pl: "Kuchnia", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Salon", pl: "Salon", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Salle de bain", pl: "Łazienka", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Toilette", pl: "Toaleta", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Garage", pl: "Garaż", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Jardin", pl: "Ogród", niveau: 1, categorie: "Maison : Pièces" },
    { fr: "Balcon", pl: "Balkon", niveau: 1, categorie: "Maison : Pièces" },

    // Maison : Meubles
    { fr: "Table", pl: "Stół", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Chaise", pl: "Krzesło", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Lit", pl: "Łóżko", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Canapé", pl: "Kanapa", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Armoire", pl: "Szafa", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Fenêtre", pl: "Okno", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Porte", pl: "Drzwi", niveau: 1, categorie: "Maison : Meubles" },
    { fr: "Lampe", pl: "Lampa", niveau: 1, categorie: "Maison : Meubles" },

    // Transports
    { fr: "Voiture", pl: "Samochód", niveau: 1, categorie: "Transports" },
    { fr: "Bus", pl: "Autobus", niveau: 1, categorie: "Transports" },
    { fr: "Train", pl: "Pociąg", niveau: 1, categorie: "Transports" },
    { fr: "Avion", pl: "Samolot", niveau: 1, categorie: "Transports" },
    { fr: "Vélo", pl: "Rower", niveau: 1, categorie: "Transports" },
    { fr: "Bateau", pl: "Statek", niveau: 1, categorie: "Transports" },
    { fr: "Métro", pl: "Metro", niveau: 1, categorie: "Transports" },
    { fr: "Taxi", pl: "Taksówka", niveau: 1, categorie: "Transports" },
    { fr: "Billet", pl: "Bilet", niveau: 1, categorie: "Transports" },
    { fr: "Gare", pl: "Dworzec", niveau: 1, categorie: "Transports" },

    // Professions
    { fr: "Médecin", pl: "Lekarz", niveau: 1, categorie: "Professions" },
    { fr: "Professeur", pl: "Nauczyciel", niveau: 1, categorie: "Professions" },
    { fr: "Policier", pl: "Policjant", niveau: 1, categorie: "Professions" },
    { fr: "Acteur", pl: "Aktor", niveau: 1, categorie: "Professions" },
    { fr: "Étudiant", pl: "Student", niveau: 1, categorie: "Professions" },
    { fr: "Ingénieur", pl: "Inżynier", niveau: 1, categorie: "Professions" },
    { fr: "Avocat", pl: "Prawnik", niveau: 1, categorie: "Professions" },
    { fr: "Vendeur", pl: "Sprzedawca", niveau: 1, categorie: "Professions" },
    { fr: "Chanteur", pl: "Piosenkarz", niveau: 1, categorie: "Professions" },

    // Nature et Paysages
    { fr: "Arbre", pl: "Drzewo", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Fleur", pl: "Kwiat", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Forêt", pl: "Las", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Montagne", pl: "Góra", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Rivière", pl: "Rzeka", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Mer", pl: "Morze", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Plage", pl: "Plaża", niveau: 1, categorie: "Nature et Paysages" },
    { fr: "Ciel", pl: "Niebo", niveau: 1, categorie: "Nature et Paysages" },

    // Météo et Climat
    { fr: "Soleil", pl: "Słońce", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Pluie", pl: "Deszcz", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Neige", pl: "Śnieg", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Vent", pl: "Wiatr", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Nuage", pl: "Chmura", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Chaud (Météo)", pl: "Ciepło", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Froid (Météo)", pl: "Zimno", niveau: 1, categorie: "Météo et Climat" },
    { fr: "Tempête", pl: "Burza", niveau: 1, categorie: "Météo et Climat" },

    // Émotions et Sentiments
    { fr: "Heureux", pl: "Szczęśliwy", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Triste", pl: "Smutny", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "En colère", pl: "Zły", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Surpris", pl: "Zaskoczony", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Amour", pl: "Miłość", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Peur", pl: "Strach", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Joie", pl: "Radość", niveau: 1, categorie: "Émotions et Sentiments" },
    { fr: "Stressé", pl: "Zestresowany", niveau: 1, categorie: "Émotions et Sentiments" },

    // Informatique et Tech
    { fr: "Ordinateur", pl: "Komputer", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Internet", pl: "Internet", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Mot de passe", pl: "Hasło", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Fichier", pl: "Plik", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Dossier", pl: "Folder", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Télécharger", pl: "Pobrać", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Site web", pl: "Strona", niveau: 1, categorie: "Informatique et Tech" },
    { fr: "Message", pl: "Wiadomość", niveau: 1, categorie: "Informatique et Tech" },

    // École et Éducation
    { fr: "Livre", pl: "Książka", niveau: 1, categorie: "École et Éducation" },
    { fr: "Cahier", pl: "Zeszyt", niveau: 1, categorie: "École et Éducation" },
    { fr: "Stylo", pl: "Długopis", niveau: 1, categorie: "École et Éducation" },
    { fr: "Crayon", pl: "Ołówek", niveau: 1, categorie: "École et Éducation" },
    { fr: "Examen", pl: "Egzamin", niveau: 1, categorie: "École et Éducation" },
    { fr: "Leçon", pl: "Lekcja", niveau: 1, categorie: "École et Éducation" },
    { fr: "Classe", pl: "Klasa", niveau: 1, categorie: "École et Éducation" },
    { fr: "Devoirs", pl: "Praca domowa", niveau: 1, categorie: "École et Éducation" },

    // Survie et Urgences
    { fr: "Aide", pl: "Pomoc", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Urgence", pl: "Wypadek", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Police", pl: "Policja", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Ambulance", pl: "Karetka", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Danger", pl: "Niebezpieczeństwo", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Attention", pl: "Uwaga", niveau: 1, categorie: "Survie et Urgences" },
    { fr: "Au secours", pl: "Ratunku", niveau: 1, categorie: "Survie et Urgences" },

    // Divers
    { fr: "Argent", pl: "Pieniądze", niveau: 1, categorie: "Divers" },
    { fr: "Carte de crédit", pl: "Karta", niveau: 1, categorie: "Divers" },
    { fr: "Problème", pl: "Problem", niveau: 1, categorie: "Divers" },
    { fr: "Question", pl: "Pytanie", niveau: 1, categorie: "Divers" },
    { fr: "Chose", pl: "Rzecz", niveau: 1, categorie: "Divers" },
    { fr: "Idée", pl: "Pomysł", niveau: 1, categorie: "Divers" },
    { fr: "Erreur", pl: "Błąd", niveau: 1, categorie: "Divers" },
    { fr: "Vérité", pl: "Prawda", niveau: 1, categorie: "Divers" }
];

const verbes = [
    { fr: "Être", pl: "Być", groupe: "irrégulier", conjugaisons: ["jestem", "jesteś", "jest", "jesteśmy", "jesteście", "są"] },
    { fr: "Avoir", pl: "Mieć", groupe: "-m / -sz", conjugaisons: ["mam", "masz", "ma", "mamy", "macie", "mają"] },
    { fr: "Faire", pl: "Robić", groupe: "-ę / -isz", conjugaisons: ["robię", "robisz", "robi", "robimy", "robicie", "robią"] },
    { fr: "Aller", pl: "Iść", groupe: "irrégulier", conjugaisons: ["idę", "idziesz", "idzie", "idziemy", "idziecie", "idą"] },
    { fr: "Pouvoir", pl: "Móc", groupe: "-ę / -esz", conjugaisons: ["mogę", "możesz", "może", "możemy", "możecie", "mogą"] },
    { fr: "Vouloir", pl: "Chcieć", groupe: "-ę / -esz", conjugaisons: ["chcę", "chcesz", "chce", "chcemy", "chcecie", "chcą"] },
    { fr: "Savoir", pl: "Wiedzieć", groupe: "irrégulier", conjugaisons: ["wiem", "wiesz", "wie", "wiemy", "wiecie", "wiedzą"] },
    { fr: "Parler", pl: "Mówić", groupe: "-ę / -isz", conjugaisons: ["mówię", "mówisz", "mówi", "mówimy", "mówicie", "mówią"] },
    { fr: "Voir", pl: "Widzieć", groupe: "-ę / -isz", conjugaisons: ["widzę", "widzisz", "widzi", "widzimy", "widzicie", "widzą"] },
    { fr: "Penser", pl: "Myśleć", groupe: "-ę / -isz", conjugaisons: ["myślę", "myślisz", "myśli", "myślimy", "myślicie", "myślą"] },
    { fr: "Comprendre", pl: "Rozumieć", groupe: "-m / -sz", conjugaisons: ["rozumiem", "rozumiesz", "rozumie", "rozumiemy", "rozumiecie", "rozumieją"] },
    { fr: "Manger", pl: "Jeść", groupe: "irrégulier", conjugaisons: ["jem", "jesz", "je", "jemy", "jecie", "jedzą"] },
    { fr: "Boire", pl: "Pić", groupe: "-ję / -jesz", conjugaisons: ["piję", "pijesz", "pije", "pijemy", "pijecie", "piją"] },
    { fr: "Dormir", pl: "Spać", groupe: "-ię / -isz", conjugaisons: ["śpię", "śpisz", "śpi", "śpimy", "śpicie", "śpią"] },
    { fr: "Aimer (quelque chose)", pl: "Lubić", groupe: "-ię / -isz", conjugaisons: ["lubię", "lubisz", "lubi", "lubimy", "lubicie", "lubią"] },
    { fr: "Aimer (quelqu'un)", pl: "Kochać", groupe: "-am / -asz", conjugaisons: ["kocham", "kochasz", "kocha", "kochamy", "kochacie", "kochają"] },
    { fr: "Travailler", pl: "Pracować", groupe: "-uję / -ujesz", conjugaisons: ["pracuję", "pracujesz", "pracuje", "pracujemy", "pracujecie", "pracują"] },
    { fr: "Acheter", pl: "Kupować", groupe: "-uję / -ujesz", conjugaisons: ["kupuję", "kupujesz", "kupuje", "kupujemy", "kupujecie", "kupują"] },
    { fr: "Chercher", pl: "Szukać", groupe: "-am / -asz", conjugaisons: ["szukam", "szukasz", "szuka", "szukamy", "szukacie", "szukają"] },
    { fr: "Donner", pl: "Dać", groupe: "irrégulier", conjugaisons: ["dam", "dasz", "da", "damy", "dacie", "dadzą"] }
];

const chiffres = [
    { num: 0, pl: "zero" },
    { num: 1, pl: "jeden" },
    { num: 2, pl: "dwa" },
    { num: 3, pl: "trzy" },
    { num: 4, pl: "cztery" },
    { num: 5, pl: "pięć" },
    { num: 6, pl: "sześć" },
    { num: 7, pl: "siedem" },
    { num: 8, pl: "osiem" },
    { num: 9, pl: "dziewięć" },
    { num: 10, pl: "dziesięć" },
    { num: 11, pl: "jedenaście" },
    { num: 12, pl: "dwanaście" },
    { num: 20, pl: "dwadzieścia" },
    { num: 30, pl: "trzydzieści" },
    { num: 40, pl: "czterdzieści" },
    { num: 50, pl: "pięćdziesiąt" },
    { num: 60, pl: "sześćdziesiąt" },
    { num: 70, pl: "siedemdziesiąt" },
    { num: 80, pl: "osiemdziesiąt" },
    { num: 90, pl: "dziewięćdziesiąt" },
    { num: 100, pl: "sto" },
    { num: 200, pl: "dwieście" },
    { num: 1000, pl: "tysiąc" },
    { num: 10000, pl: "dziesięć tysięcy" },
    { num: 100000, pl: "sto tysięcy" },
    { num: 1000000, pl: "milion" }
];

const jours = [
    { fr: "Lundi", pl: "Poniedziałek" },
    { fr: "Mardi", pl: "Wtorek" },
    { fr: "Mercredi", pl: "Środa" },
    { fr: "Jeudi", pl: "Czwartek" },
    { fr: "Vendredi", pl: "Piątek" },
    { fr: "Samedi", pl: "Sobota" },
    { fr: "Dimanche", pl: "Niedziela" }
];

const mois = [
    { fr: "Janvier", pl: "Styczeń", gen: "stycznia" },
    { fr: "Février", pl: "Luty", gen: "lutego" },
    { fr: "Mars", pl: "Marzec", gen: "marca" },
    { fr: "Avril", pl: "Kwiecień", gen: "kwietnia" },
    { fr: "Mai", pl: "Maj", gen: "maja" },
    { fr: "Juin", pl: "Czerwiec", gen: "czerwca" },
    { fr: "Juillet", pl: "Lipiec", gen: "lipca" },
    { fr: "Août", pl: "Sierpień", gen: "sierpnia" },
    { fr: "Septembre", pl: "Wrzesień", gen: "września" },
    { fr: "Octobre", pl: "Październik", gen: "października" },
    { fr: "Novembre", pl: "Listopad", gen: "listopada" },
    { fr: "Décembre", pl: "Grudzień", gen: "grudnia" }
];
